version: '1'

services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/cerbot/conf:/etc/letsencrypt
      - ./data/cerbot/www:/var/www/certbot
    container_name: timebook-proxy
    depends_on:
      - api
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  api:
    image: m2162003/timebook-api
    ports:
      - 8080:8080
    container_name: timebook-api

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - ./data/cerbot/conf:/etc/letsencrypt
      - ./data/cerbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"